# Generated by Django 4.2 on 2025-04-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="order",
            new_name="cart_order_created_27f3c7_idx",
            old_name="cart_order_created_4a0a00_idx",
        ),
    ]
